"""empty message

Revision ID: 498a4e521b1a
Revises: 7daa29bb687e
Create Date: 2023-03-09 20:25:30.719841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "498a4e521b1a"
down_revision = "7daa29bb687e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_tag_association",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_tag_association_article_id_articles")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_article_tag_association_tag_id_tags")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_tag_association")
    # ### end Alembic commands ###
