"""update user model

Revision ID: 6d734bd81d5b
Revises: a398bff0103e
Create Date: 2023-03-03 21:18:15.551257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d734bd81d5b"
down_revision = "a398bff0103e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(length=120), server_default="", nullable=False))
        batch_op.add_column(sa.Column("last_name", sa.String(length=120), server_default="", nullable=False))
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
