"""empty message

Revision ID: 7daa29bb687e
Revises: 53ea07496d12
Create Date: 2023-03-09 20:18:20.045626

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7daa29bb687e"
down_revision = "53ea07496d12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    # ### end Alembic commands ###
